format:
  html:
    self-contained: true
    theme: cosmo
    css: styles.css
    
    
project:
  type: website
  output-dir: docs

website:
  title: "Lab 3: Visualizing COVID's Takeover"
  navbar:
   left:
     - href: index.qmd
       text: Home

 