---
project:
  title: "index"
  format: html
  output-dir: docs
  type: website
format:
  html:
   self-contained: true
---

# Q1.

#### Take a moment to reflect on the value of open data:

How does easy access to historical and real-time environmental data
shape our understanding of climate trends, resource management, and
public health? What happens when this data disappears or becomes
inaccessible? The role of independent archiving and collaborative
stewardship has never been more critical in ensuring scientific progress
and accountability.

1.  When we can access historical and real-time data, we're better able to draw connections between previous conditions and the present to identify trends over time. We can see how present observations fit with previous data, which is the most important evidence that climate change is happening. When these data are accessible to everyone, we can hold our leaders accountable for the decisions they make, which are supposed to be on behalf of the public. Natural resource management is a very rough science that can be heavily influenced by policies, so access to data over time is crucial for holding agencies accountable in processes like the National Environmental Policy Act, where the public has a chance to influence agency actions, or the actions of any major actor on natural resources, or to identify trends over time that have multiple influences. When the data disappear or become inaccessible, people can get away with lying to support ulterior motives and decision makers can make choices with catastrophic consequences.

# Q2.Daily Summary

# Conditions to Meet for CO Public Health
 For **More than 100 new cases in Colorado per 100,000 residents over the past 14
    days**, report also:

1.  cumulative cases in the 5 worst counties
2.  total NEW cases in the 5 worst counties
3.  A list of safe counties
4.  A text report describing the total new cases,
5.  total cumulative cases, and number of safe counties.

### Steps Q2

1.  Start by reading in the data from the NY-Times URL with read_csv
    (make sure to attach the tidyverse)
```{r, echo = TRUE}

library(dplyr)
library(tidyverse)
library(flextable)
library(zoo)
data = read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv')
```